### PR TITLE
#75, Changed sort order of breakpoints to descending

### PR DESCRIPTION
**Pull request by dn-achim**
As explained by rigor789 at https://github.com/baianat/hooper/issues/75

### CODE REVIEW

**Comment by Abdelrahman3D** [comment]
Thank you for help! (closes #75)

**Comment by Abdelrahman3D** [comment]
Okay, I will.

**Comment by leandromatos-hotmart** [comment]
The version of this package on NPM doesn't have this breakpoint feature yet, right?

**Comment by Abdelrahman3D** [comment]
This feature is shipped with version `0.1.4`, if you had any issue with breakpoints, please report it.

**Comment by nhattran998** [comment]
> This feature is shipped with version `0.1.4`, if you had any issue with breakpoints, please report it.
image

I don't know why but in mobile device => itemsToShow = 2 it's not working!
I use the current version(^0.3.4), hope you can help me resolve that! @ismail9k

**Comment by ismail9k** [comment]
Hello @harrytran998, sorry but this project is no longer maintained by me.

**Pull request merged**
